name:                tcamerge
version:             0.1.0.0
homepage:            https://github.com/theoremprover/tcamerge#readme
license:             BSD3
author:              Robert Reitmeier
maintainer:          haskell@thinking-machines.net
copyright:           2021 Robert Reitmeier

dependencies:
  - base >= 4.7 && < 5

executables:
  tcamerge-exe:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
    - -threaded
